/*
 * Linux_EdgeSys_Base.c - Main application for Linux
 */

#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
#include <time.h>
#include "thread.h"
#include "channel.h"
#include "labels.h"

// These will be generated by the code generator
#include "sysConfig.h"
#include "labels_conf.h"
#include "channel_conf.h"
#include "user_runnables.h"

static bool application_running = true;

void signal_handler(int signum) {
    printf("Received signal %d, shutting down...\n", signum);
    application_running = false;
    thread_killThreads();
}

int main(int argc, char* argv[]) {
    printf("Starting Linux EdgeSys Base Application\n");
    
    // Set up signal handling
    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);
    
    // Initialize subsystems
    channel_init();
    labels_init();
    
    // Register threads (generated code)
    REGISTER_THREADS;
    
    // Initialize runnables
    thread_initRunnables();
    
    // Create and start threads
    thread_createThreads();
    
    // Main loop
    printf("Application running... Press Ctrl+C to stop\n");
    while (application_running) {
        sleep(1);
    }
    
    // Cleanup
    thread_deinitRunnables();
    thread_joinThreads();
    
    printf("Application terminated\n");
    return 0;
}